#!/usr/bin/env bash
set -euo pipefail

# setup-dev-env.sh — build the Python/protobuf toolchain this repo needs.
#
# Two pinned versions, and they are pinned to what the FLEET runs, not to what
# is newest:
#
#   protoc 3.21.12          regenerates NodeInfo_pb2.py
#   protobuf 4.21.12        the runtime nodes actually have
#
# Both directions matter. Nodes' 4.21.12 runtime rejects generated code from
# protoc older than 3.19, and protoc 5.x emits a `runtime_version` gate that
# 4.21.12 does not have — so the window is narrow and both edges are real.
# Testing against a *newer* protobuf than the fleet has is worse than not
# testing: it accepts pb2 files the nodes will refuse to import.
#
# Everything lands in one venv, protoc included. That is deliberate: activating
# it puts the correct compiler on PATH as well as the correct runtime, so there
# is no way to have one without the other.
#
#   source ~/.venvs/manet/bin/activate
#   protoc --version                       # libprotoc 3.21.12
#   python -m unittest discover -s MANET/node_tools -p 'test_*.py'
#
# Why this script exists: the capability was lost once already. The committed
# NodeInfo_pb2.py was built with protoc 3.21.x, but no such protoc remained on
# the dev machine — only Ubuntu's /usr/bin/protoc 3.12.4, whose output the
# whole fleet refuses to import. Nothing detected that, because the system
# protobuf runtime was too old to tell the difference either.
#
# Needs no root. Nothing outside $VENV_DIR is touched.

VENV_DIR="${MANET_VENV_DIR:-$HOME/.venvs/manet}"
PROTOC_VERSION="21.12"          # release tag; reports itself as libprotoc 3.21.12
PROTOBUF_RUNTIME="4.21.12"
PROTOC_SHA256="3a4c1e5f2516c639d3079b1586e703fc7bcfa2136d58bda24d1d54f949c315e8"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

case "$(uname -m)" in
    x86_64)         PROTOC_ARCH=linux-x86_64 ;;
    aarch64|arm64)  PROTOC_ARCH=linux-aarch_64; PROTOC_SHA256="" ;;
    *) echo "ERROR: no protoc build mapped for $(uname -m)" >&2; exit 1 ;;
esac

echo "==> venv: $VENV_DIR"
if [ ! -x "$VENV_DIR/bin/python" ]; then
    # --without-pip because Ubuntu splits ensurepip into python3.x-venv, which
    # is not installed by default and needs root. pip is bootstrapped below
    # instead, so this stays a no-sudo setup.
    python3 -m venv --without-pip "$VENV_DIR"
fi

if [ ! -x "$VENV_DIR/bin/pip" ]; then
    echo "==> bootstrapping pip"
    tmp_getpip="$(mktemp -d)"
    trap 'rm -rf "$tmp_getpip"' EXIT
    curl -fsSL https://bootstrap.pypa.io/pip/get-pip.py -o "$tmp_getpip/get-pip.py"
    "$VENV_DIR/bin/python" "$tmp_getpip/get-pip.py" --quiet
fi

echo "==> protobuf runtime $PROTOBUF_RUNTIME"
"$VENV_DIR/bin/pip" install --quiet "protobuf==$PROTOBUF_RUNTIME"

if [ "$("$VENV_DIR/bin/protoc" --version 2>/dev/null)" != "libprotoc 3.$PROTOC_VERSION" ]; then
    echo "==> protoc $PROTOC_VERSION"
    tmp_protoc="$(mktemp -d)"
    zip="$tmp_protoc/protoc.zip"
    curl -fsSL -o "$zip" \
        "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-${PROTOC_ARCH}.zip"
    if [ -n "$PROTOC_SHA256" ]; then
        echo "$PROTOC_SHA256  $zip" | sha256sum -c - >/dev/null \
            || { echo "ERROR: protoc checksum mismatch — refusing to install" >&2
                 rm -rf "$tmp_protoc"; exit 1; }
    fi
    unzip -q "$zip" -d "$tmp_protoc"
    install -m 0755 "$tmp_protoc/bin/protoc" "$VENV_DIR/bin/protoc"
    mkdir -p "$VENV_DIR/include"
    cp -a "$tmp_protoc/include/." "$VENV_DIR/include/"
    rm -rf "$tmp_protoc"
fi

echo ""
echo "==> verifying"
"$VENV_DIR/bin/protoc" --version
"$VENV_DIR/bin/python" -c "import google.protobuf as p; print('protobuf runtime', p.__version__)"

# The real check: this toolchain must reproduce the committed NodeInfo_pb2.py
# byte for byte. If it does not, either the pin here is wrong or the checked-in
# file was generated by something else — and either way, regenerating would
# produce a diff that has nothing to do with the .proto change being made.
echo ""
echo "==> reproducing the committed NodeInfo_pb2.py"
check="$(mktemp -d)"
cp "$REPO_ROOT/MANET/node_tools/NodeInfo.proto" "$check/"
( cd "$check" && "$VENV_DIR/bin/protoc" --python_out=. NodeInfo.proto )
if diff -q "$check/NodeInfo_pb2.py" "$REPO_ROOT/MANET/node_tools/NodeInfo_pb2.py" >/dev/null; then
    echo "    byte-identical — toolchain is correct"
else
    echo "    MISMATCH against the committed NodeInfo_pb2.py:" >&2
    diff "$check/NodeInfo_pb2.py" "$REPO_ROOT/MANET/node_tools/NodeInfo_pb2.py" | head -20 >&2
    rm -rf "$check"
    exit 1
fi
rm -rf "$check"

cat <<MSG

Ready. Use it with:

    source $VENV_DIR/bin/activate

    # run the tests against the runtime nodes actually have
    python -m unittest discover -s MANET/node_tools -p 'test_*.py'

    # regenerate after editing NodeInfo.proto (from MANET/node_tools/)
    protoc --python_out=. NodeInfo.proto

Do NOT use /usr/bin/protoc — it is 3.12.4 on this distro and its output is
rejected by every node.
MSG
