# Updated r3a section for linux.sh
# Replace the existing r3a block in the "Starting hardware imaging" section
# 
# IMPORTANT: This uses Armbian's built-in provisioning mechanism.
# Armbian's armbian-firstlogin script sources /root/provisioning.sh at the end.
# We do NOT need a separate systemd service.

if [ "$HARDWARE_MODEL" = "r3a" ]; then
	# Create temp copy of image to avoid modifying original
	TEMP_IMAGE=$(mktemp --suffix=.img)
	echo "Creating temporary copy of Armbian image..."
	cp "$ARMBIAN_IMAGE" "$TEMP_IMAGE"

	# Loop mount the temp image
	LOOP_DEV=$(sudo losetup -fP --show "$TEMP_IMAGE")
	echo "Mounted image as: $LOOP_DEV"
	
	# Mount root partition (partition 2 on Armbian - partition 1 is /boot)
	ROOT_MOUNT="/tmp/armbian-root"
	sudo mkdir -p "$ROOT_MOUNT"
	echo "Mounting ${LOOP_DEV}p2 to $ROOT_MOUNT"
	sudo mount "${LOOP_DEV}p2" "$ROOT_MOUNT"

	# Write mesh configuration to /etc/mesh.conf
	echo "Writing /etc/mesh.conf..."
	sudo tee "$ROOT_MOUNT/etc/mesh.conf" > /dev/null << EOF
# Mesh Network Configuration
# Generated by provisioning script on $(date)
hardware_model=${HARDWARE_MODEL}
eud=${EUD_CONNECTION}
lan_ap_ssid=${LAN_AP_SSID}
lan_ap_key=${LAN_AP_KEY}
max_euds_per_node=${MAX_EUDS_PER_NODE}
mtx=${INSTALL_MEDIAMTX}
mumble=${INSTALL_MUMBLE}
mesh_ssid=${MESH_SSID}
mesh_key=${MESH_SAE_KEY}
ipv4_network=${LAN_CIDR_BLOCK}
acs=${AUTO_CHANNEL}
regulatory_domain=${REGULATORY_DOMAIN}
EOF

	# Create Armbian firstrun preset file
	echo "Writing /root/.not_logged_in_yet..."
	sudo tee "$ROOT_MOUNT/root/.not_logged_in_yet" > /dev/null << 'EOF'
# Network Settings
PRESET_NET_CHANGE_DEFAULTS="1"
## Ethernet
PRESET_NET_ETHERNET_ENABLED="1"
## WiFi
PRESET_NET_WIFI_ENABLED="0"
PRESET_NET_USE_STATIC="0"
# System
SET_LANG_BASED_ON_LOCATION="y"
PRESET_LOCALE="en_US.UTF-8"
PRESET_TIMEZONE="Etc/UTC"
# Root
PRESET_ROOT_PASSWORD="root"
PRESET_ROOT_KEY=""
# User
PRESET_USER_NAME="radio"
PRESET_USER_PASSWORD="radio"
PRESET_USER_KEY=""
PRESET_DEFAULT_REALNAME="radio"
PRESET_USER_SHELL="bash"
EOF

	# Write the provisioning script (sourced by armbian-firstlogin)
	echo "Writing /root/provisioning.sh..."
	sudo tee "$ROOT_MOUNT/root/provisioning.sh" > /dev/null << 'PROVISIONEOF'
#!/bin/bash
#
# Armbian Rock 3A Mesh Node Provisioning Script
# This script is sourced by armbian-firstlogin after user creation
#

# Don't use set -x when sourced - it will spam the console
# Log to file instead
PROVISION_LOG="/var/log/mesh-provision.log"

{
    echo "=== Rock 3A provisioning starting at $(date) ==="

    # Source the mesh configuration
    if [ -f /etc/mesh.conf ]; then
        source /etc/mesh.conf
    else
        echo "ERROR: /etc/mesh.conf not found!"
        # Don't exit - we're sourced, just return
        return 1 2>/dev/null || true
    fi

    # Set regulatory domain
    REG="${regulatory_domain:-US}"

    # Calculate unique hostname from MAC address
    HOST_MAC=$(ip a | grep -A1 "$(ip -o link show | awk -F': ' '/^[0-9]+: e/ {print $2; exit}')" \
       | awk '/ether/ {print $2}' | cut -d':' -f 5-6 | sed 's/://g')
    if [ -n "$HOST_MAC" ]; then
        hostnamectl set-hostname "mesh-${HOST_MAC}"
        echo "Hostname set to mesh-${HOST_MAC}"
    fi

    echo "Waiting for internet connectivity..."
    TIMEOUT=300
    ELAPSED=0
    while [ $ELAPSED -lt $TIMEOUT ]; do
        if ping -c 1 -W 2 8.8.8.8 > /dev/null 2>&1; then
            echo "Internet connectivity confirmed!"
            break
        fi
        echo "Waiting for internet... (${ELAPSED}s)"
        sleep 5
        ELAPSED=$((ELAPSED + 5))
    done

    if [ $ELAPSED -ge $TIMEOUT ]; then
        echo "ERROR: No internet after ${TIMEOUT}s"
        return 1 2>/dev/null || true
    fi

    # Set system time
    date -s "$(curl -sI google.com | grep -i ^Date: | cut -d' ' -f2-)" 2>/dev/null || true

    cd /root

    # Clear motd
    > /etc/motd

    # Update system packages FIRST (before extracting tarball to avoid kernel overwrites)
    echo "Updating system packages..."
    apt-get update > /dev/null 2>&1
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y > /dev/null 2>&1

    # Remove the question about the iperf daemon during apt install
    echo "iperf3 iperf3/start_daemon boolean true" | debconf-set-selections

    # Install required packages
    echo "Installing required packages..."
    DEBIAN_FRONTEND=noninteractive apt-get install -y ipcalc nmap lshw tcpdump net-tools nftables wireless-tools iperf3 \
        radvd bridge-utils firmware-mediatek libnss-mdns syncthing networkd-dispatcher \
        libgps-dev libcap-dev screen arping bc jq git libssl-dev hostapd dnsmasq \
        python3-protobuf unzip chrony build-essential systemd-resolved dhcping \
        libnl-3-dev libnl-genl-3-dev libnl-route-3-dev ebtables libdbus-1-dev gpsd

    # Download the install package
    echo "Downloading Rock 3A install package..."
    wget -q https://www.colorado-governor.com/manet/r3a-install.tar.gz -O /root/morse-pi-install.tar.gz || {
        echo "ERROR: Failed to download Rock 3A install package"
        return 1 2>/dev/null || true
    }

    # Unpack the install tarball AFTER apt updates to avoid kernel overwrites
    echo "Extracting install package..."
    tar -zxf /root/morse-pi-install.tar.gz -C /

    # Disable dnsmasq (we'll configure it ourselves)
    systemctl stop dnsmasq
    systemctl disable dnsmasq
    systemctl mask dnsmasq

    # Remove old avahi/yq if present
    apt-get remove -y avahi yq > /dev/null 2>&1 || true

    # Install Go yq
    wget -q https://github.com/mikefarah/yq/releases/latest/download/yq_linux_arm64 -O /usr/bin/yq
    chmod +x /usr/bin/yq

    # Disable automatic update timers
    systemctl disable apt-daily.timer > /dev/null 2>&1 || true
    systemctl disable apt-daily-upgrade.timer > /dev/null 2>&1 || true

    # Load modules at boot
    cat << MODEOF > /etc/modules-load.d/morse.conf
mac80211
cfg80211
crc7
morse
dot11ah
MODEOF

    # Morse driver options
    cat << MODEOF > /etc/modprobe.d/morse.conf
options morse country=${REG}
options morse enable_mcast_whitelist=0 enable_mcast_rate_control=1
MODEOF

    # Set regulatory domain
    iw reg set "$REG" 2>/dev/null || true

    # Make sure tools are executable
    chmod +x /usr/local/bin/* 2>/dev/null || true

    # Use known DNS
    rm -f /etc/resolv.conf
    echo "nameserver 1.1.1.1" > /etc/resolv.conf

    # Clean up
    rm -f /root/morse-pi-install.tar.gz

    # Remove this script so it doesn't run again
    rm -f /root/provisioning.sh

    echo "=== Rock 3A provisioning complete at $(date) ==="

} >> "$PROVISION_LOG" 2>&1

# Show user that provisioning completed
echo ""
echo "Mesh node provisioning complete. See $PROVISION_LOG for details."
echo "System will reboot in 10 seconds to apply changes..."
echo ""

# Schedule reboot after this script returns (don't reboot while sourced)
( sleep 10 && reboot ) &
PROVISIONEOF

	sudo chmod +x "$ROOT_MOUNT/root/provisioning.sh"

	# Unmount
	echo "Unmounting image..."
	sudo sync
	sudo umount "$ROOT_MOUNT"
	sudo rmdir "$ROOT_MOUNT"
	sudo losetup -d "$LOOP_DEV"

	# Wipe target device to avoid stale partition data
	echo "Wiping target device..."
	sudo wipefs -a "$TARGET_DEVICE"

	# Flash to device
	echo "Flashing image to $TARGET_DEVICE..."
	sudo dd if="$TEMP_IMAGE" of="$TARGET_DEVICE" bs=4M status=progress conv=fsync
	sudo sync

	# Clean up temp image
	rm -f "$TEMP_IMAGE"

	echo "Flash complete!"

else
	# Raspberry Pi path - use rpi-imager
	sudo rpi-imager --cli "$PI_OS_IMAGE_URL" "$TARGET_DEVICE" --first-run-script "$TEMP_SCRIPT_FILE"
fi
