#!/bin/bash
TARGET_IFACE="end0"

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] - GATEWAY-UP [$$]($IFACE): $1" | systemd-cat -t mesh-gateway
}

if [ "$IFACE" != "$TARGET_IFACE" ]; then
    exit 0
fi

log "Ethernet state change on $IFACE - running auto-detection..."
/usr/local/bin/ethernet-autodetect.sh
