#!/bin/bash
#
#  This script enslaves various interfaces to the bat0 batman bridge
#
#  Standard 802.11 mesh interfaces (wpa_supplicant):
#    - Set to mesh point mode via ip link, wait for iw confirmation, then add to bat0
#
#  HaLow / 802.11ah interfaces (wpa_supplicant_s1g):
#    - Already in S1G mesh mode managed by wpa_supplicant_s1g
#    - DO NOT set type mesh (will fail / interrupt the S1G driver)
#    - Just wait for interface UP, then add to bat0
#

set -e

# Source mesh configuration to get the MESH_NAME variable
if [ -f /etc/default/mesh ]; then
    source /etc/default/mesh
else
    echo "Error: Mesh configuration /etc/default/mesh not found!" >&2
    exit 1
fi

iface_driver() {
    local iface="$1"
    local driver

    driver="$(basename "$(readlink -f /sys/class/net/$iface/device/driver 2>/dev/null)")"
    if [[ -z "$driver" || "$driver" == "." ]]; then
        driver="$(ethtool -i "$iface" 2>/dev/null | awk -F': ' '$1 == "driver" {print $2; exit}')"
    fi

    echo "$driver"
}

iface_phy() {
    local iface="$1"
    iw dev "$iface" info 2>/dev/null | awk '/wiphy/ {print "phy"$2; exit}'
}

iface_supports_mesh() {
    local iface="$1"
    local phyname

    phyname="$(iface_phy "$iface")"
    [[ -n "$phyname" ]] && iw phy "$phyname" info 2>/dev/null | grep -q "mesh point"
}

is_halow() {
    [[ "$(iface_driver "$1")" == morse* ]]
}

is_nonmesh_wifi() {
    [[ "$(iface_driver "$1")" == brcmfmac ]]
}

radio_iface_enabled() {
    python3 - "$1" <<'PY'
import json, sys
iface = sys.argv[1]
try:
    with open('/var/lib/mesh_radio_state.json') as f:
        state = json.load(f).get('desired', {}).get(iface, 'up')
except Exception:
    state = 'up'
sys.exit(1 if state == 'down' else 0)
PY
}

refresh_interfaces() {
    STANDARD_MESH_INTERFACES=""
    HALOW_INTERFACES=""
    NONMESH_INTERFACES=""

    # Prefer role files written by radio-setup. This is important when a Morse
    # USB device exists but is intentionally disabled because the driver can
    # create a netdev that times out on link-up.
    if [ -s /var/lib/mesh_if ] || [ -s /var/lib/halow_if ] || [ -s /var/lib/no_mesh_if ]; then
        # Wait for role-file interfaces to appear in sysfs (drivers may be slow at boot)
        local all_ifaces
        all_ifaces="$(cat /var/lib/mesh_if /var/lib/halow_if /var/lib/no_mesh_if 2>/dev/null | tr '\n' ' ')"
        for WLAN in $all_ifaces; do
            for i in $(seq 1 20); do
                [ -d "/sys/class/net/$WLAN" ] && break
                [ "$i" -eq 20 ] && echo "Warning: $WLAN did not appear in sysfs after 20s, continuing" >&2
                sleep 1
            done
        done

        for WLAN in $(cat /var/lib/mesh_if 2>/dev/null); do
            [ -d "/sys/class/net/$WLAN" ] && STANDARD_MESH_INTERFACES+="$WLAN "
        done
        for WLAN in $(cat /var/lib/halow_if 2>/dev/null); do
            [ -d "/sys/class/net/$WLAN" ] && HALOW_INTERFACES+="$WLAN "
        done
        for WLAN in $(cat /var/lib/no_mesh_if 2>/dev/null); do
            [ -d "/sys/class/net/$WLAN" ] && NONMESH_INTERFACES+="$WLAN "
        done

        echo "Role-file wireless classification:"
        echo "  Standard mesh: $STANDARD_MESH_INTERFACES"
        echo "  HaLow: $HALOW_INTERFACES"
        echo "  Non-mesh/AP: $NONMESH_INTERFACES"
        return
    fi

    WLAN_INTERFACES="$(iw dev 2>/dev/null | awk '$1 == "Interface" {print $2}' | tr '\n' ' ')"

    for WLAN in $WLAN_INTERFACES; do
        if is_halow "$WLAN"; then
            HALOW_INTERFACES+="$WLAN "
        elif is_nonmesh_wifi "$WLAN"; then
            NONMESH_INTERFACES+="$WLAN "
        elif iface_supports_mesh "$WLAN"; then
            STANDARD_MESH_INTERFACES+="$WLAN "
        else
            NONMESH_INTERFACES+="$WLAN "
        fi
    done

    echo "Runtime wireless classification:"
    echo "  Standard mesh: $STANDARD_MESH_INTERFACES"
    echo "  HaLow: $HALOW_INTERFACES"
    echo "  Non-mesh/AP: $NONMESH_INTERFACES"
}

start() {
    echo "Starting BATMAN-ADV setup..."
    refresh_interfaces

    # -------------------------------------------------------------------------
    # Ensure wpa_supplicant is running for all mesh interfaces.
    # batman-enslave.service may have been generated by an older radio-setup.sh
    # that lacked proper After=wpa_supplicant@wlanX.service dependencies.
    # Starting the services here makes batman-if-setup.sh self-sufficient.
    # -------------------------------------------------------------------------
    for WLAN in $STANDARD_MESH_INTERFACES; do
        if ! radio_iface_enabled "$WLAN"; then
            echo "Skipping wpa_supplicant for $WLAN (radio-state says down)"
            systemctl stop "wpa_supplicant@${WLAN}.service" 2>/dev/null || true
            ip link set "$WLAN" down 2>/dev/null || true
            continue
        fi
        if ! systemctl is-active "wpa_supplicant@${WLAN}.service" >/dev/null 2>&1; then
            echo "Starting wpa_supplicant for $WLAN..."
            systemctl start "wpa_supplicant@${WLAN}.service" 2>/dev/null || \
                echo "Warning: could not start wpa_supplicant for $WLAN (config may be missing)" >&2
        fi
    done
    for WLAN in $HALOW_INTERFACES; do
        local svc="wpa_supplicant-s1g-${WLAN}.service"
        if ! radio_iface_enabled "$WLAN"; then
            echo "Skipping $svc for $WLAN (radio-state says down)"
            systemctl stop "$svc" 2>/dev/null || true
            ip link set "$WLAN" down 2>/dev/null || true
            continue
        fi
        if ! systemctl is-active "$svc" >/dev/null 2>&1; then
            echo "Starting wpa_supplicant_s1g for $WLAN..."
            systemctl start "$svc" 2>/dev/null || \
                echo "Warning: could not start $svc" >&2
        fi
    done

    # -------------------------------------------------------------------------
    # Write udev .link files for all discovered interfaces if they are missing.
    # Without these files, kernel names wlanX by probe order which can change
    # across reboots, making role files point at the wrong physical radio.
    # -------------------------------------------------------------------------
    local wrote_links=false
    for WLAN in $STANDARD_MESH_INTERFACES $HALOW_INTERFACES $NONMESH_INTERFACES; do
        local link_file="/etc/systemd/network/10-${WLAN}.link"
        if [ ! -f "$link_file" ]; then
            local mac
            mac=$(cat "/sys/class/net/${WLAN}/address" 2>/dev/null || true)
            if [ -n "$mac" ]; then
                printf '[Match]\nMACAddress=%s\n\n[Link]\nName=%s\n' "$mac" "$WLAN" > "$link_file"
                echo "Wrote $link_file (MAC=$mac)"
                wrote_links=true
            fi
        fi
    done
    [ "$wrote_links" = true ] && networkctl reload 2>/dev/null || true

    # Change to batman V routing algorithm
    batctl ra BATMAN_V

    # Create bat0 interface if it doesn't exist
    ip link show bat0 &>/dev/null || ip link add name bat0 type batadv

    # Set gateway mode based on state
    if [ -f /var/run/mesh-gateway.state ]; then
        batctl gw_mode server
        echo "Set to gateway server mode"
    else
        batctl gw_mode client
        echo "Set to gateway client mode"
    fi

# -------------------------------------------------------------------------
    # HaLow / 802.11ah interfaces (added FIRST to become batman-adv primary)
    #
    # HaLow is the longest-range link and most likely to remain connected when
    # standard 802.11ax peers are out of range. Making it the primary ensures
    # batman-adv continues generating and processing OGMs even when all
    # standard mesh interfaces go inactive.
    #
    # wpa_supplicant_s1g owns these devices. Do NOT call 'ip link set type mesh'
    # on an S1G interface. Some Morse driver builds do not report operstate UP
    # even when batman-adv can enslave the interface, so wait for the netdev to
    # exist and let batctl's retry loop decide whether the interface is usable.
    # -------------------------------------------------------------------------
    for WLAN in $HALOW_INTERFACES; do
        if ! radio_iface_enabled "$WLAN"; then
            echo "--> Skipping HaLow interface: $WLAN (radio-state says down)"
            systemctl stop "wpa_supplicant-s1g-${WLAN}.service" 2>/dev/null || true
            ip link set "$WLAN" down 2>/dev/null || true
            continue
        fi
        echo "--> Configuring HaLow interface: $WLAN (primary)"

        echo "Waiting for $WLAN netdev (managed by wpa_supplicant_s1g)..."
        for i in {1..30}; do
            if ip link show "$WLAN" >/dev/null 2>&1; then
                ip link set "$WLAN" up 2>/dev/null || true
                echo "$WLAN exists."
                break
            fi
            if [ $i -eq 30 ]; then
                echo "!! Timed out waiting for $WLAN. Skipping." >&2
                continue 2
            fi
            sleep 1
        done

        ip link set "$WLAN" mtu 1532 2>/dev/null || true

        echo "Adding HaLow $WLAN to bat0..."

        ADDED=false
        for attempt in {1..5}; do
            if batctl bat0 if add "$WLAN" 2>&1; then
                sleep 0.5
                if batctl bat0 if | grep -q "$WLAN"; then
                    echo "$WLAN successfully added to bat0 (primary interface)"
                    ADDED=true
                    break
                else
                    echo "Attempt $attempt: $WLAN not showing in batctl, retrying..."
                fi
            else
                echo "Attempt $attempt: batctl add failed, retrying..."
            fi
            sleep 1
        done

        if [ "$ADDED" = false ]; then
            echo "!! ERROR: Failed to add HaLow $WLAN to bat0 after 5 attempts" >&2
            echo "!! This interface will not participate in the mesh" >&2
        fi
    done

    # -------------------------------------------------------------------------
    # Standard 802.11 mesh interfaces
    # -------------------------------------------------------------------------
    for WLAN in $STANDARD_MESH_INTERFACES; do
        if ! radio_iface_enabled "$WLAN"; then
            echo "--> Skipping standard mesh interface: $WLAN (radio-state says down)"
            systemctl stop "wpa_supplicant@${WLAN}.service" 2>/dev/null || true
            ip link set "$WLAN" down 2>/dev/null || true
            continue
        fi
        echo "--> Configuring standard mesh interface: $WLAN"

        echo "Waiting for $WLAN to be in mesh point mode (managed by wpa_supplicant)..."
        for i in {1..30}; do
            if iw dev "$WLAN" info 2>/dev/null | grep -q "type mesh point"; then
                echo "$WLAN is in mesh point mode."
                break
            fi
            if [ $i -eq 30 ]; then
                echo "!! Timed out waiting for $WLAN to enter mesh point mode. Skipping." >&2
                continue 2
            fi
            sleep 1
        done

        sleep 2

        ip link set "$WLAN" mtu 1532 2>/dev/null || true

        echo "Adding $WLAN to bat0..."

        ADDED=false
        for attempt in {1..5}; do
            if batctl bat0 if add "$WLAN" 2>&1; then
                sleep 0.5
                if batctl bat0 if | grep -q "$WLAN"; then
                    echo "$WLAN successfully added to bat0"
                    ADDED=true
                    break
                else
                    echo "Attempt $attempt: $WLAN not showing in batctl, retrying..."
                fi
            else
                echo "Attempt $attempt: batctl add failed, retrying..."
            fi
            sleep 1
        done

        if [ "$ADDED" = false ]; then
            echo "!! ERROR: Failed to add $WLAN to bat0 after 5 attempts" >&2
            echo "!! This interface will not participate in the mesh" >&2
        fi
    done

    ip link set bat0 up
    echo "bat0 interface is up and configured."

    # Final verification
    echo ""
    echo "=== Final bat0 membership ==="
    batctl bat0 if
    echo "============================="
}

# Clear out bat0
stop() {
    echo "Stopping BATMAN-ADV..."
    refresh_interfaces
    for WLAN in $STANDARD_MESH_INTERFACES $HALOW_INTERFACES; do
        if batctl bat0 if | grep -q "$WLAN"; then
            batctl bat0 if del "$WLAN"
        fi
    done
    ip link show bat0 &>/dev/null && ip link del bat0
}

case "$1" in
    start|stop)
        "$1"
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
