#!/bin/bash
# ==============================================================================
# Mesh Node Manager - Static Channel Mode
# ==============================================================================
# Simplified version for static channel operation
# - No RF scanning or channel selection
# - No tourguide (all nodes on same channels always)
# - Just publishes status and manages services
# ==============================================================================

# --- Configuration ---
CONTROL_IFACE="br0"
ALFRED_DATA_TYPE=68
MONITOR_INTERVAL=15

# Static channels (lobby channels used as permanent data channels)
STATIC_FREQ_2_4=2412
STATIC_FREQ_5_0=5180

# Radio Config. The mesh interface names are generated by radio-setup and may
# be runtime names during first provisioning, so do not hardcode wlan indexes.
WPA_CONF_2_4=""
WPA_CONF_5_0=""
WPA_IFACE_2_4=""
WPA_IFACE_5_0=""

# Helper scripts
REGISTRY_BUILDER="/usr/local/bin/mesh-registry-builder.sh"
IP_MANAGER="/usr/local/bin/mesh-ip-manager.sh"
REGISTRY_STATE_FILE="/var/run/mesh_node_registry"
ENCODER_PATH="/usr/local/bin/encoder.py"
BATCTL_PATH="/usr/sbin/batctl"
RADIO_STATE_SYNC="/usr/local/bin/mesh-radio-state.py"
HALOW_MCS_SUMMARY="/usr/local/bin/halow-mcs-summary.py"

# --- State Variables ---
LAST_PUBLISHED_PAYLOAD=""
LAST_PUBLISH_TIME=0
PUBLISH_INTERVAL=180  # Publish every 3 minutes

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] - NODE-MGR-STATIC: $1" >&2
}


# ==============================================================================
# === GATEWAY DETECTION ===
# ==============================================================================
# Gateway state is owned by manet-uplink-dispatch.sh. Node manager only
# asks it to reconcile periodically before publishing status to Alfred.
GATEWAY_STATE_FILE="/var/run/mesh-gateway.state"
LAST_GW_CHECK=0
GW_CHECK_INTERVAL=60

detect_and_update_gateway_state() {
    local NOW
    NOW=$(date +%s)

    local time_since_check=$(( NOW - LAST_GW_CHECK ))
    if [ "$time_since_check" -lt "$GW_CHECK_INTERVAL" ] && [ -f "$GATEWAY_STATE_FILE" ]; then
        return
    fi

    LAST_GW_CHECK=$NOW
    [ -x /usr/local/bin/manet-uplink-dispatch.sh ] && /usr/local/bin/manet-uplink-dispatch.sh reconcile >/dev/null 2>&1 || true
}

get_current_freq() {
    local conf_file=$1
    grep -oP 'frequency=\K[0-9]+' "$conf_file" 2>/dev/null | head -1
}

radio_iface_enabled() {
    python3 - "$1" <<'PY'
import json, sys
iface = sys.argv[1]
try:
    with open('/var/lib/mesh_radio_state.json') as f:
        state = json.load(f).get('desired', {}).get(iface, 'up')
except Exception:
    state = 'up'
sys.exit(1 if state == 'down' else 0)
PY
}

collect_radio_mcs() {
    WLAN0_TX_MCS=""; WLAN0_RX_MCS=""
    WLAN1_TX_MCS=""; WLAN1_RX_MCS=""
    WLAN2_TX_MCS=""; WLAN2_RX_MCS=""
    [ -x "$HALOW_MCS_SUMMARY" ] || return 0
    for iface in wlan0 wlan1 wlan2; do
        [ -d "/sys/class/net/$iface" ] || continue
        eval "$("$HALOW_MCS_SUMMARY" --iface "$iface" --shell 2>/dev/null || true)"
    done
}

load_mesh_wpa_confs() {
    local mesh_ifaces=()

    if [ -f /var/lib/mesh_if ]; then
        mapfile -t mesh_ifaces < /var/lib/mesh_if
    fi

    WPA_IFACE_2_4="${mesh_ifaces[0]:-wlan0}"
    WPA_IFACE_5_0="${mesh_ifaces[1]:-wlan1}"
    WPA_CONF_2_4="/etc/wpa_supplicant/wpa_supplicant-${WPA_IFACE_2_4}.conf"
    WPA_CONF_5_0="/etc/wpa_supplicant/wpa_supplicant-${WPA_IFACE_5_0}.conf"
}

ensure_static_channels() {
    load_mesh_wpa_confs

    if [ ! -f "$WPA_CONF_2_4" ] || [ ! -f "$WPA_CONF_5_0" ]; then
        log "Static mesh WPA configs not ready: $WPA_CONF_2_4 / $WPA_CONF_5_0"
        return
    fi

    local freq_2_4=$(get_current_freq "$WPA_CONF_2_4")
    local freq_5_0=$(get_current_freq "$WPA_CONF_5_0")
    
    local needs_restart=false
    
    if [ "$freq_2_4" != "$STATIC_FREQ_2_4" ]; then
        log "Correcting 2.4 GHz to static channel $STATIC_FREQ_2_4"
        sed -i "s/frequency=.*/frequency=${STATIC_FREQ_2_4}/" "$WPA_CONF_2_4"
        needs_restart=true
    fi
    
    if [ "$freq_5_0" != "$STATIC_FREQ_5_0" ]; then
        log "Correcting 5 GHz to static channel $STATIC_FREQ_5_0"
        sed -i "s/frequency=.*/frequency=${STATIC_FREQ_5_0}/" "$WPA_CONF_5_0"
        needs_restart=true
    fi
    
    if [ "$needs_restart" = true ]; then
        log "Restarting wpa_supplicant services..."
        radio_iface_enabled "$WPA_IFACE_2_4" && systemctl restart "wpa_supplicant@${WPA_IFACE_2_4}.service"
        radio_iface_enabled "$WPA_IFACE_5_0" && systemctl restart "wpa_supplicant@${WPA_IFACE_5_0}.service"
        sleep 5
    fi
}

is_hosting_service() {
	if systemctl is-active --quiet mediamtx.service; then

	# Source the network configuration
	if [ -f /etc/mesh.conf ]; then
	    # Parse the config file
	    while IFS='=' read -r key value; do
	        [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
	        case "$key" in
	            ipv4_network)
	                IPV4_NETWORK="$value"
	                ;;
	        esac
	    done < /etc/mesh.conf
	fi

        local CALC_OUTPUT=$(ipcalc "$IPV4_NETWORK" 2>/dev/null)
        local FIRST_IP=$(echo "$CALC_OUTPUT" | awk '/HostMin/ {print $2}')
        local MEDIAMTX_IPV4_VIP="${FIRST_IP%.*}.$((${FIRST_IP##*.} + 1))"
        ip addr show dev "$CONTROL_IFACE" | grep -q "inet $MEDIAMTX_IPV4_VIP/" && return 0
    fi
    return 1
}

is_hosting_mumble_service() {
    if systemctl is-active --quiet mumble-server.service; then
        if [ -f /etc/mesh.conf ]; then
            while IFS='=' read -r key value; do
                [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
                case "$key" in
                    ipv4_network)
                        IPV4_NETWORK="$value"
                        ;;
                esac
            done < /etc/mesh.conf
        fi

        local CALC_OUTPUT
        CALC_OUTPUT=$(ipcalc "$IPV4_NETWORK" 2>/dev/null)
        local FIRST_IP
        FIRST_IP=$(echo "$CALC_OUTPUT" | awk '/HostMin/ {print $2}')
        local MUMBLE_IPV4_VIP="${FIRST_IP%.*}.$((${FIRST_IP##*.} + 2))"
        ip addr show dev "$CONTROL_IFACE" | grep -q "inet $MUMBLE_IPV4_VIP/" && return 0
    fi
    return 1
}

# === MAIN SETUP ===
log "Starting Mesh Node Manager (Static Channel Mode)."
log "Static channels: 2.4G=${STATIC_FREQ_2_4}, 5G=${STATIC_FREQ_5_0}"
MY_MAC=$(cat "/sys/class/net/${CONTROL_IFACE}/address")
log "Node MAC: ${MY_MAC}"

# Ensure we're on static channels at startup
ensure_static_channels

# === MAIN LOOP ===
while true; do
    NOW=$(date +%s)

    # === ALFRED RADIO STATE SYNC ===
    # Global radio up/down changes are staged through Alfred and only applied
    # after all nodes have ACKed the same version.
    [ -x "$RADIO_STATE_SYNC" ] && "$RADIO_STATE_SYNC" sync || true

    # Load current chunk assignment from IP manager
    MY_CHUNK=0
    if [ -f /var/run/my_ipv4_chunk ]; then
        MY_CHUNK=$(cat /var/run/my_ipv4_chunk)
    fi
    # === PERIODIC CHANNEL CHECK ===
    # Verify we haven't drifted from static channels (safety check)
    ensure_static_channels
    
    # === REGISTRY BUILD ===
    [ -x "$REGISTRY_BUILDER" ] && "$REGISTRY_BUILDER"
    
    # === IP MANAGEMENT ===
    [ -x "$IP_MANAGER" ] && "$IP_MANAGER"
    
    # === PUBLISH STATUS ===
    time_since_publish=$((NOW - LAST_PUBLISH_TIME))
    
    if [ $time_since_publish -ge $PUBLISH_INTERVAL ]; then
        log "Publishing status to Alfred..."
        
        HOSTNAME=$(hostname)
        SYNCTHING_ID=$(runuser -u radio -- syncthing --device-id 2>/dev/null || echo "")
        TQ_AVG=$("$BATCTL_PATH" o 2>/dev/null | awk 'NR>1 {sum+=$3} END {if (NR>1) printf "%.2f", sum/(NR-1); else print 0}')
        
        # Service flags
        detect_and_update_gateway_state
        IS_GATEWAY_FLAG=$([ -f /var/run/mesh-gateway.state ] && echo "--is-internet-gateway" || echo "")
        GATEWAY_IFACE=$(cat /var/run/upstream_iface 2>/dev/null || echo "")
        IS_NTP_FLAG=$([ -f /var/run/mesh-ntp.state ] && echo "--is-ntp-server" || echo "")
        IS_MEDIAMTX_FLAG=$(is_hosting_service && echo "--is-mediamtx-server" || echo "")
        IS_MUMBLE_FLAG=$(is_hosting_mumble_service && echo "--is-mumble-server" || echo "")
        
        # Gather MACs
        ALL_MACS=("$MY_MAC")
        for iface in /sys/class/net/wlan* /sys/class/net/bat0 /sys/class/net/end0; do
            iface=$(basename "$iface")
            if [ -d "/sys/class/net/$iface" ]; then
                MAC=$(cat "/sys/class/net/$iface/address" 2>/dev/null)
                [ -n "$MAC" ] && ALL_MACS+=("$MAC")
            fi
        done
        
        CURRENT_IPV4=$(ip addr show dev "$CONTROL_IFACE" 2>/dev/null | grep -oP 'inet \K[\d.]+' | head -1)
        collect_radio_mcs
        
        # Encode (no scan data, no limp mode, no tourguide in static mode)
        ENCODER_ARGS=(
            "--hostname" "$HOSTNAME"
            "--mac-addresses" "${ALL_MACS[@]}"
            "--tq-average" "$TQ_AVG"
            "--syncthing-id" "$SYNCTHING_ID"
            "--ipv4-chunk" "$MY_CHUNK"
            "--timestamp" "$NOW"
            "--data-channel-2-4" "$STATIC_FREQ_2_4"
            "--data-channel-5-0" "$STATIC_FREQ_5_0"
            "--wifi-24-tx-mcs" "${WLAN0_TX_MCS:-}"
            "--wifi-24-rx-mcs" "${WLAN0_RX_MCS:-}"
            "--wifi-5-tx-mcs" "${WLAN1_TX_MCS:-}"
            "--wifi-5-rx-mcs" "${WLAN1_RX_MCS:-}"
            "--halow-tx-mcs" "${WLAN2_TX_MCS:-}"
            "--halow-rx-mcs" "${WLAN2_RX_MCS:-}"
            "--halow-mcs-peer" "${WLAN2_MCS_PEER:-}"
        )
        [ -n "$CURRENT_IPV4" ] && ENCODER_ARGS+=("--ipv4-address" "$CURRENT_IPV4")
        [ -n "$IS_GATEWAY_FLAG" ] && ENCODER_ARGS+=("$IS_GATEWAY_FLAG")
        [ -n "$GATEWAY_IFACE" ] && ENCODER_ARGS+=("--gateway-iface" "$GATEWAY_IFACE")
        [ -n "$IS_NTP_FLAG" ] && ENCODER_ARGS+=("$IS_NTP_FLAG")
        [ -n "$IS_MEDIAMTX_FLAG" ] && ENCODER_ARGS+=("$IS_MEDIAMTX_FLAG")
        [ -n "$IS_MUMBLE_FLAG" ] && ENCODER_ARGS+=("$IS_MUMBLE_FLAG")
        BATT_PCT=$(python3 -c "import json;d=json.load(open('/run/battery_status.json'));print(d['percentage'])" 2>/dev/null)
        [ -n "$BATT_PCT" ] && ENCODER_ARGS+=("--battery-percentage" "$BATT_PCT")
        UPTIME_SECS=$(awk '{print int($1)}' /proc/uptime 2>/dev/null)
        [ -n "$UPTIME_SECS" ] && ENCODER_ARGS+=("--uptime-seconds" "$UPTIME_SECS")
        CPU_LOAD=$(awk '{print $1}' /proc/loadavg 2>/dev/null)
        [ -n "$CPU_LOAD" ] && ENCODER_ARGS+=("--cpu-load-average" "$CPU_LOAD")

        CURRENT_PAYLOAD=$("$ENCODER_PATH" "${ENCODER_ARGS[@]}" 2>/dev/null)
        
        if [ -n "$CURRENT_PAYLOAD" ]; then
            echo -n "$CURRENT_PAYLOAD" | alfred -s $ALFRED_DATA_TYPE
            LAST_PUBLISHED_PAYLOAD="$CURRENT_PAYLOAD"
            LAST_PUBLISH_TIME=$NOW
        fi
    fi
	# === RUN SERVICE ELECTIONS ===
	for election_script in /usr/local/bin/*-election.sh; do
	    if [[ -f "$election_script" && -x "$election_script" ]]; then
	        # Skip channel-election.sh since we're static
	        [[ "$election_script" =~ channel-election ]] && continue
	        # Skip mediamtx-election.sh if MTX not enabled
	        if [[ "$election_script" =~ mediamtx-election ]]; then
	            MTX_ENABLED=$(grep "^mtx=" /etc/mesh.conf 2>/dev/null | cut -d'=' -f2)
	            [[ "$MTX_ENABLED" != "y" ]] && continue
	        fi
	        if [[ "$election_script" =~ mumble-election ]]; then
	            MUMBLE_ENABLED=$(grep "^mumble=" /etc/mesh.conf 2>/dev/null | cut -d'=' -f2)
	            [[ "$MUMBLE_ENABLED" != "y" ]] && continue
	        fi
	        "$election_script" &    # ← NOW runs only if checks pass
	    fi
	done
    sleep "$MONITOR_INTERVAL"
done

log "Main loop exited unexpectedly. Restarting..."
exit 1
