#!/bin/bash
# Mesh Node Manager - Static Channel Mode
# Simplified version for static channel operation
# - No RF scanning or channel selection
# - No tourguide (all nodes on same channels always)
# - Just publishes status and manages services

# --- Configuration ---
CONTROL_IFACE="br0"
ALFRED_IDENTITY_TYPE=67
ALFRED_DATA_TYPE=68
MONITOR_INTERVAL=15
STARTUP_MONITOR_INTERVAL=1

# Static channels come from the stored plan (manet_static_channels.py), which
# defaults to the lobby channels. Empty until the plan has been read.
STATIC_CHANNELS="${MANET_STATIC_CHANNELS_TOOL:-/usr/local/bin/manet_static_channels.py}"
STATIC_FREQ_2_4=""
STATIC_FREQ_5_0=""
# The radio apply path writes the plan and supplicant files under this lock.
CHANNEL_LOCK_FILE="${MANET_ACS_LOCK_FILE:-/var/run/channel-election.lock}"

# Radio Config. The mesh interface names are generated by radio-setup and may
# be runtime names during first provisioning, so do not hardcode wlan indexes.
WPA_CONF_2_4=""
WPA_CONF_5_0=""
WPA_IFACE_2_4=""
WPA_IFACE_5_0=""

# Helper scripts
IP_MANAGER="/usr/local/bin/mesh-ip-manager.sh"
REGISTRY_STATE_FILE="/var/run/mesh_node_registry"
ENCODER_PATH="/usr/local/bin/encoder.py"
BATCTL_PATH="/usr/sbin/batctl"
THROUGHPUT_MEAN="/usr/local/bin/mesh-throughput-mean.sh"
RADIO_STATE_SYNC="/usr/local/bin/mesh-radio-state.py"
CONFIG_SYNC="/usr/local/bin/mesh-config-sync.py"
CONFIG_ROLLBACK="/usr/local/bin/mesh-config-rollback.sh"
HALOW_MCS_SUMMARY="/usr/local/bin/halow-mcs-summary.py"

# --- State Variables ---
LAST_PUBLISHED_PAYLOAD=""
LAST_PUBLISH_TIME=0
PUBLISH_INTERVAL=180  # Publish every 3 minutes

# Identity has a slow keepalive; startup and allocation changes publish sooner.
# Alfred purges any record it has not seen for ALFRED_DATA_TIMEOUT = 600 s, so
# at 270 s a publish can fail once and the record still survives.
LAST_IDENTITY_PUBLISH=0
LAST_IDENTITY_ALLOCATION=""
LAST_ACK_PUBLISHED=""
SYNCTHING_ID=""
CLOCK_READY_SEEN=false
IDENTITY_PUBLISH_INTERVAL=270

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] - NODE-MGR-STATIC: $1" >&2
}


# === GATEWAY DETECTION ===
# Gateway state is owned by manet-uplink-dispatch.sh. Node manager only
# asks it to reconcile periodically before publishing status to Alfred.
GATEWAY_STATE_FILE="/var/run/mesh-gateway.state"
LAST_GW_CHECK=0
GW_CHECK_INTERVAL=60

detect_and_update_gateway_state() {
    local NOW
    NOW=$(date +%s)

    local time_since_check=$(( NOW - LAST_GW_CHECK ))
    if [ "$time_since_check" -lt "$GW_CHECK_INTERVAL" ] && [ -f "$GATEWAY_STATE_FILE" ]; then
        return
    fi

    LAST_GW_CHECK=$NOW
    [ -x /usr/local/bin/manet-uplink-dispatch.sh ] && /usr/local/bin/manet-uplink-dispatch.sh reconcile >/dev/null 2>&1 || true
}

# Time source advertisement (the time service owns chrony and these markers)
GPS_STATUS_FILE="/run/gps_status.json"
GPS_FIX_MAX_AGE=60

is_ntp_time_source() {
    local run_dir="${MANET_TIME_RUN_DIR:-/run}"
    [ -f "$run_dir/mesh-ntp.state" ] || [ -f "$run_dir/mesh-ntp-gps.state" ]
}

get_current_freq() {
    local conf_file=$1
    grep -oP 'frequency=\K[0-9]+' "$conf_file" 2>/dev/null | head -1
}

radio_iface_enabled() {
    python3 - "$1" <<'PY'
import json, sys
iface = sys.argv[1]
try:
    with open('/var/lib/mesh_radio_state.json') as f:
        state = json.load(f).get('desired', {}).get(iface, 'up')
except Exception:
    state = 'up'
sys.exit(1 if state == 'down' else 0)
PY
}

collect_radio_mcs() {
    WLAN0_TX_MCS=""; WLAN0_RX_MCS=""
    WLAN1_TX_MCS=""; WLAN1_RX_MCS=""
    WLAN2_TX_MCS=""; WLAN2_RX_MCS=""
    [ -x "$HALOW_MCS_SUMMARY" ] || return 0
    for iface in wlan0 wlan1 wlan2; do
        [ -d "/sys/class/net/$iface" ] || continue
        eval "$("$HALOW_MCS_SUMMARY" --iface "$iface" --shell 2>/dev/null || true)"
    done
}

collect_interfaces_json() {
    python3 /usr/local/bin/mesh-status.py --dump-interfaces 2>/dev/null || echo '[]'
}

# The SSID hostapd actually broadcasts (base name plus node suffix), not the
# base value in mesh.conf.
collect_ap_ssid() {
    python3 /usr/local/bin/manet_eud_ap.py current 2>/dev/null || true
}

# Service elections choose the holder of a shared VIP. Run them only once this
# node holds an address allocation: until discovery has finished (complete, or
# at its bounded deadline) the registry may contain only this node, which then
# always wins and takes a VIP a peer still holds. Also run them at most once per
# steady interval, not on every one-second startup pass. Local locks and this
# gate reduce churn; they cannot guarantee a single holder across a partition,
# which the elections resolve once the registries converge.
ELECTION_INTERVAL=15
LAST_ELECTION_RUN=""
run_service_elections() {
    local now election_script
    [ -s /var/run/my_ipv4_chunk ] || return 0
    read -r now _ < "${MESH_UPTIME_FILE:-/proc/uptime}"
    now=${now%.*}
    if [ -n "$LAST_ELECTION_RUN" ] && [ $((now - LAST_ELECTION_RUN)) -lt "$ELECTION_INTERVAL" ]; then
        return 0
    fi
    LAST_ELECTION_RUN=$now
    for election_script in "${ELECTION_DIR:-/usr/local/bin}"/*-election.sh; do
        [[ -f "$election_script" && -x "$election_script" ]] || continue
        # Channel election has its own schedule (ACS) or does not apply (static)
        [[ "$election_script" =~ channel-election ]] && continue
        if [[ "$election_script" =~ mediamtx-election ]]; then
            [[ "$(grep "^mtx=" /etc/mesh.conf 2>/dev/null | cut -d'=' -f2)" == "y" ]] || continue
        fi
        if [[ "$election_script" =~ mumble-election ]]; then
            [[ "$(grep "^mumble=" /etc/mesh.conf 2>/dev/null | cut -d'=' -f2)" == "y" ]] || continue
        fi
        "$election_script" &
    done
}

# Band roles come from radio-setup's role files, as in ACS mode. Position in
# mesh_if is not a band: a node with a single 5 GHz mesh radio lists it first.
# An empty role file means that band has no mesh radio (the 5 GHz radio may be
# reserved for AP duty).
load_mesh_wpa_confs() {
    local roles="${MANET_IFACE_STATE_DIR:-/var/lib}"
    local configs="${MANET_WPA_DIR:-/etc/wpa_supplicant}"
    WPA_IFACE_2_4=$(cat "$roles/mesh_24_if" 2>/dev/null || true)
    WPA_IFACE_5_0=$(cat "$roles/mesh_5_if" 2>/dev/null || true)
    WPA_CONF_2_4=""; WPA_CONF_5_0=""
    [ -z "$WPA_IFACE_2_4" ] || WPA_CONF_2_4="$configs/wpa_supplicant-${WPA_IFACE_2_4}.conf"
    [ -z "$WPA_IFACE_5_0" ] || WPA_CONF_5_0="$configs/wpa_supplicant-${WPA_IFACE_5_0}.conf"
}

ensure_static_iface_channel() {
    local iface=$1 conf=$2 static_freq=$3 band=$4
    local lobby="${conf%.conf}-lobby.conf"

    [ -n "$iface" ] && [ -n "$static_freq" ] || return 0
    if [ ! -f "$conf" ]; then
        log "Static mesh WPA config not ready for $band: $conf"
        return 0
    fi

    # mesh-boot-lobby copies the lobby file over the live one at every boot,
    # so keep it on the plan too. It needs no restart.
    if [ -f "$lobby" ] && [ "$(get_current_freq "$lobby")" != "$static_freq" ]; then
        sed -i "s/frequency=.*/frequency=${static_freq}/" "$lobby"
    fi

    local freq
    freq=$(get_current_freq "$conf")
    [ "$freq" = "$static_freq" ] && return 0

    log "Correcting $band to static channel $static_freq"
    sed -i "s/frequency=.*/frequency=${static_freq}/" "$conf"
    if radio_iface_enabled "$iface"; then
        log "Restarting wpa_supplicant@${iface}..."
        systemctl restart "wpa_supplicant@${iface}.service"
        STATIC_SETTLE=true
    fi
}

# Read the stored plan. An unreadable or malformed plan is reported and the
# radios are left alone, not moved to guessed defaults.
load_static_plan() {
    local f24 f5
    if f24=$(python3 "$STATIC_CHANNELS" get 2.4 2>&1) && f5=$(python3 "$STATIC_CHANNELS" get 5 2>&1); then
        STATIC_FREQ_2_4=$f24
        STATIC_FREQ_5_0=$f5
        return 0
    fi
    log "ERROR: static channel plan unusable, not enforcing channels: ${f5:-$f24}"
    return 1
}

ensure_static_channels() {
    # Take the lock the radio apply path holds across plan save, file writes,
    # readiness checks and rollback BEFORE reading the plan, and hold it until
    # enforcement is done, so a half-applied or rolled-back change is never
    # read or undone. Non-blocking: a change in progress skips this pass.
    exec {lock_fd}>"$CHANNEL_LOCK_FILE"
    if ! flock -n "$lock_fd"; then
        exec {lock_fd}>&-
        return 0
    fi
    STATIC_SETTLE=false
    if load_static_plan; then
        load_mesh_wpa_confs
        ensure_static_iface_channel "$WPA_IFACE_2_4" "$WPA_CONF_2_4" "$STATIC_FREQ_2_4" "2.4 GHz"
        ensure_static_iface_channel "$WPA_IFACE_5_0" "$WPA_CONF_5_0" "$STATIC_FREQ_5_0" "5 GHz"
    fi
    exec {lock_fd}>&-
    # Let a restarted supplicant come up, without holding the channel lock.
    [ "$STATIC_SETTLE" = true ] && sleep 5
    return 0
}

is_hosting_service() {
	if systemctl is-active --quiet mediamtx.service; then
        local IPV4_NETWORK=""
	# Source the network configuration
	if [ -f /etc/mesh.conf ]; then
	    # Parse the config file
	    while IFS='=' read -r key value; do
	        [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
	        case "$key" in
	            ipv4_network)
	                IPV4_NETWORK="$value"
	                ;;
	        esac
	    done < /etc/mesh.conf
	fi
        [ -z "$IPV4_NETWORK" ] && return 1

        local CALC_OUTPUT=$(manet-ipcalc.sh "$IPV4_NETWORK" 2>/dev/null)
        local FIRST_IP=$(echo "$CALC_OUTPUT" | awk '/HostMin/ {print $2}')
        local MEDIAMTX_IPV4_VIP="${FIRST_IP%.*}.$((${FIRST_IP##*.} + 1))"
        ip addr show dev "$CONTROL_IFACE" | grep -q "inet $MEDIAMTX_IPV4_VIP/" && return 0
    fi
    return 1
}

is_hosting_mumble_service() {
    if systemctl is-active --quiet mumble-server.service; then
        if [ -f /etc/mesh.conf ]; then
            while IFS='=' read -r key value; do
                [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
                case "$key" in
                    ipv4_network)
                        IPV4_NETWORK="$value"
                        ;;
                esac
            done < /etc/mesh.conf
        fi

        local CALC_OUTPUT
        CALC_OUTPUT=$(manet-ipcalc.sh "$IPV4_NETWORK" 2>/dev/null)
        local FIRST_IP
        FIRST_IP=$(echo "$CALC_OUTPUT" | awk '/HostMin/ {print $2}')
        local MUMBLE_IPV4_VIP="${FIRST_IP%.*}.$((${FIRST_IP##*.} + 2))"
        ip addr show dev "$CONTROL_IFACE" | grep -q "inet $MUMBLE_IPV4_VIP/" && return 0
    fi
    return 1
}

# === MAIN SETUP ===
log "Starting Mesh Node Manager (Static Channel Mode)."
load_static_plan && log "Static channels: 2.4G=${STATIC_FREQ_2_4}, 5G=${STATIC_FREQ_5_0}"
MY_MAC=$(cat "/sys/class/net/${CONTROL_IFACE}/address")
log "Node MAC: ${MY_MAC}"

# Ensure we're on static channels at startup
ensure_static_channels

# === MAIN LOOP ===
while true; do
    NOW=$(date +%s)

    if [ "$CLOCK_READY_SEEN" = false ] && [ -f "${MANET_TIME_RUN_DIR:-/run}/initial_time_synced" ]; then
        CLOCK_READY_SEEN=true
        LAST_PUBLISH_TIME=0; LAST_IDENTITY_PUBLISH=0; LAST_GW_CHECK=0
    fi

    # === ALFRED RADIO STATE SYNC ===
    # Global radio up/down changes are staged through Alfred and only applied
    # after all nodes have ACKed the same version.
    [ -x "$RADIO_STATE_SYNC" ] && "$RADIO_STATE_SYNC" sync || true

    # === ALFRED CONFIG SYNC ===
    # Same shape for mesh configuration: stage what the operator broadcast,
    # publish an ACK, and apply once activate_at passes.
    [ -x "$CONFIG_SYNC" ] && "$CONFIG_SYNC" sync || true

    # A dangerous config change can take the mesh down. This is the node
    # deciding, on its own, whether the change worked or has to be undone.
    [ -x "$CONFIG_ROLLBACK" ] && "$CONFIG_ROLLBACK" check || true

    # An ACK is only useful if peers see it promptly, so a change here brings
    # the next telemetry publish forward instead of waiting out the interval.
    CURRENT_ACK=$(cat /var/run/mesh_config_ack_version 2>/dev/null || echo "")
    if [ "$CURRENT_ACK" != "$LAST_ACK_PUBLISHED" ]; then
        LAST_PUBLISH_TIME=0
        LAST_ACK_PUBLISHED="$CURRENT_ACK"
    fi

    # === PERIODIC CHANNEL CHECK ===
    # Verify we haven't drifted from static channels (safety check)
    ensure_static_channels
    
    # Established nodes check claims before publishing any allocation changes.
    # Cold nodes first publish below, so discovery can see our own records on
    # this pass instead of waiting through another complete manager loop.
    if [ -s /var/run/my_ipv4_chunk ]; then
        [ -x "$IP_MANAGER" ] && "$IP_MANAGER"
    fi
    
    # === PUBLISH IDENTITY (Alfred type 67) ===
    # Publish during discovery and whenever allocation changes; 270 s is only
    # the keepalive interval once configured. Zero is a valid chunk.
    MY_CHUNK=$(cat /var/run/my_ipv4_chunk 2>/dev/null || true)
    CURRENT_IPV4=$(python3 /usr/local/bin/manet_node_ipv4.py "$CONTROL_IFACE" 2>/dev/null || true)
    [ -z "$MY_CHUNK" ] && CURRENT_IPV4=""
    IDENTITY_ALLOCATION="${MY_CHUNK}:${CURRENT_IPV4}"
    if [ -z "$MY_CHUNK" ] || [ "$IDENTITY_ALLOCATION" != "$LAST_IDENTITY_ALLOCATION" ] ||
            [ $((NOW - LAST_IDENTITY_PUBLISH)) -ge $IDENTITY_PUBLISH_INTERVAL ]; then
        # br0's MAC must come first: encoder.py drops it, because Alfred
        # already stamps every record we publish with it.
        ALL_MACS=("$MY_MAC")
        for iface in /sys/class/net/wlan* /sys/class/net/bat0 /sys/class/net/end0; do
            iface=$(basename "$iface")
            if [ -d "/sys/class/net/$iface" ]; then
                MAC=$(cat "/sys/class/net/$iface/address" 2>/dev/null)
                [ -n "$MAC" ] && ALL_MACS+=("$MAC")
            fi
        done

        # Stable for this manager process. Retry a missing ID, but avoid starting
        # Syncthing just to read the same ID on every discovery pass.
        if [ -z "$SYNCTHING_ID" ]; then
            SYNCTHING_ID=$(timeout 3 runuser -u radio -- syncthing --device-id 2>/dev/null || true)
        fi

        IDENTITY_ARGS=(
            "--hostname" "$(hostname)"
            "--mac-addresses" "${ALL_MACS[@]}"
            "--syncthing-id" "$SYNCTHING_ID"
            "--ipv4-chunk" "${MY_CHUNK:-0}"
            "--ipv4-chunk-size" "$(cat /var/run/my_ipv4_chunk_size 2>/dev/null || echo 0)"
        )
        [ -n "$MY_CHUNK" ] && [ -n "$CURRENT_IPV4" ] && IDENTITY_ARGS+=("--ipv4-address" "$CURRENT_IPV4")

        IDENTITY_PAYLOAD=$("$ENCODER_PATH" identity "${IDENTITY_ARGS[@]}" 2>/dev/null)
        if [ -n "$IDENTITY_PAYLOAD" ]; then
            if echo -n "$IDENTITY_PAYLOAD" | alfred -s $ALFRED_IDENTITY_TYPE; then
                LAST_IDENTITY_PUBLISH=$NOW
                LAST_IDENTITY_ALLOCATION="$IDENTITY_ALLOCATION"
            fi
        else
            log "WARN: identity encoder produced no payload: $("$ENCODER_PATH" identity "${IDENTITY_ARGS[@]}" 2>&1 >/dev/null | tr '\n' ' ')"
        fi
    fi

    # === PUBLISH TELEMETRY (Alfred type 68) ===
    time_since_publish=$((NOW - LAST_PUBLISH_TIME))

    if [ ! -s /var/run/my_ipv4_chunk ] || [ $time_since_publish -ge $PUBLISH_INTERVAL ]; then
        log "Publishing status to Alfred..."

        # Not a positional field: `batctl o` shifts columns on the starred
        # (selected) route, so $3 is the last-seen timestamp there. See
        # mesh-throughput-mean.sh.
        MEAN_THROUGHPUT=$("$THROUGHPUT_MEAN" 2>/dev/null || echo 0)

        # Service flags
        detect_and_update_gateway_state
        IS_GATEWAY_FLAG=$([ -f /var/run/mesh-gateway.state ] && echo "--is-internet-gateway" || echo "")
        GATEWAY_IFACE=$(cat /var/run/upstream_iface 2>/dev/null || echo "")
        IS_NTP_FLAG=$(is_ntp_time_source && echo "--is-ntp-server" || echo "")
        IS_MEDIAMTX_FLAG=$(is_hosting_service && echo "--is-mediamtx-server" || echo "")
        IS_MUMBLE_FLAG=$(is_hosting_mumble_service && echo "--is-mumble-server" || echo "")

        collect_radio_mcs
        INTERFACES_JSON=$(collect_interfaces_json)

        # Encode (no scan data, no limp mode, no tourguide in static mode)
        ENCODER_ARGS=(
            "--mean-throughput-mbps" "$MEAN_THROUGHPUT"
            "--timestamp" "$NOW"
            "--config-ack-version" "$(cat /var/run/mesh_config_ack_version 2>/dev/null || echo "")"
            "--data-channel-2-4" "${STATIC_FREQ_2_4:-0}"
            "--data-channel-5-0" "${STATIC_FREQ_5_0:-0}"
            "--wifi-24-tx-mcs" "${WLAN0_TX_MCS:-}"
            "--wifi-24-rx-mcs" "${WLAN0_RX_MCS:-}"
            "--wifi-5-tx-mcs" "${WLAN1_TX_MCS:-}"
            "--wifi-5-rx-mcs" "${WLAN1_RX_MCS:-}"
            "--halow-tx-mcs" "${WLAN2_TX_MCS:-}"
            "--halow-rx-mcs" "${WLAN2_RX_MCS:-}"
            "--halow-mcs-peer" "${WLAN2_MCS_PEER:-}"
            "--interfaces-json" "$INTERFACES_JSON"
        )
        AP_SSID=$(collect_ap_ssid)
        [ -n "$AP_SSID" ] && ENCODER_ARGS+=("--ap-ssid" "$AP_SSID")
        [ -n "$IS_GATEWAY_FLAG" ] && ENCODER_ARGS+=("$IS_GATEWAY_FLAG")
        [ -n "$GATEWAY_IFACE" ] && ENCODER_ARGS+=("--gateway-iface" "$GATEWAY_IFACE")
        [ -n "$IS_NTP_FLAG" ] && ENCODER_ARGS+=("$IS_NTP_FLAG")
        [ -n "$IS_MEDIAMTX_FLAG" ] && ENCODER_ARGS+=("$IS_MEDIAMTX_FLAG")
        [ -n "$IS_MUMBLE_FLAG" ] && ENCODER_ARGS+=("$IS_MUMBLE_FLAG")
        BATT_PCT=$(python3 -c "import json;d=json.load(open('/run/battery_status.json'));p=d.get('percentage');print('' if p is None else p)" 2>/dev/null)
        [ -n "$BATT_PCT" ] && ENCODER_ARGS+=("--battery-percentage" "$BATT_PCT")
        UPTIME_SECS=$(awk '{print int($1)}' /proc/uptime 2>/dev/null)
        [ -n "$UPTIME_SECS" ] && ENCODER_ARGS+=("--uptime-seconds" "$UPTIME_SECS")
        CPU_LOAD=$(awk '{print $1}' /proc/loadavg 2>/dev/null)
        [ -n "$CPU_LOAD" ] && ENCODER_ARGS+=("--cpu-load-average" "$CPU_LOAD")

        # --- GPS Location ---
        # Reject stale files as well as missing fixes. If gps-reader stops updating
        # its timestamp, the last recorded position is no longer safe to publish.
        GPS_LAT=""; GPS_LON=""; GPS_ALT=""
        if [ -f "$GPS_STATUS_FILE" ]; then
            eval "$(python3 -c "
import json, sys, time
try:
    d = json.load(open(sys.argv[1]))
    if d.get('has_fix') and time.time() - d.get('timestamp', 0) <= float(sys.argv[2]):
        print('GPS_LAT=' + str(d['latitude']))
        print('GPS_LON=' + str(d['longitude']))
        print('GPS_ALT=' + str(d['altitude']))
except Exception:
    pass
" "$GPS_STATUS_FILE" "$GPS_FIX_MAX_AGE" 2>/dev/null)"
        fi
        [ -n "$GPS_LAT" ] && ENCODER_ARGS+=("--latitude" "$GPS_LAT" "--longitude" "$GPS_LON" "--altitude" "$GPS_ALT")

        CURRENT_PAYLOAD=$("$ENCODER_PATH" telemetry "${ENCODER_ARGS[@]}" 2>/dev/null)
        if [ -z "$CURRENT_PAYLOAD" ]; then
            # re-run only on failure, to surface why nothing was published
            log "WARN: encoder produced no payload, not publishing: $("$ENCODER_PATH" telemetry "${ENCODER_ARGS[@]}" 2>&1 >/dev/null | tr '\n' ' ')"
        fi
        
        if [ -n "$CURRENT_PAYLOAD" ]; then
            echo -n "$CURRENT_PAYLOAD" | alfred -s $ALFRED_DATA_TYPE
            LAST_PUBLISHED_PAYLOAD="$CURRENT_PAYLOAD"
            LAST_PUBLISH_TIME=$NOW
        fi
    fi

    # Bootstrap only after both identity and telemetry have been published.
    # The existing helper still enforces readiness and the 10/20-second wait.
    if [ ! -s /var/run/my_ipv4_chunk ]; then
        [ -x "$IP_MANAGER" ] && "$IP_MANAGER"
        if [ -s /var/run/my_ipv4_chunk ]; then
            # Publish the new claim immediately, before the steady-state sleep.
            LAST_PUBLISH_TIME=0
            continue
        fi
    fi
    # === RUN SERVICE ELECTIONS ===
    run_service_elections
    # Poll discovery promptly while waiting for the first allocation.
    if [ -s /var/run/my_ipv4_chunk ]; then
        sleep "$MONITOR_INTERVAL"
    else
        sleep "$STARTUP_MONITOR_INTERVAL"
    fi
done

log "Main loop exited unexpectedly. Restarting..."
exit 1
