#!/bin/bash
# ==============================================================================
# Mesh Node Manager - Static Channel Mode
# ==============================================================================
# Simplified version for static channel operation
# - No RF scanning or channel selection
# - No tourguide (all nodes on same channels always)
# - Just publishes status and manages services
# ==============================================================================

# --- Configuration ---
CONTROL_IFACE="br0"
ALFRED_IDENTITY_TYPE=67
ALFRED_DATA_TYPE=68
MONITOR_INTERVAL=15

# Static channels (lobby channels used as permanent data channels)
STATIC_FREQ_2_4=2412
STATIC_FREQ_5_0=5180

# Radio Config. The mesh interface names are generated by radio-setup and may
# be runtime names during first provisioning, so do not hardcode wlan indexes.
WPA_CONF_2_4=""
WPA_CONF_5_0=""
WPA_IFACE_2_4=""
WPA_IFACE_5_0=""

# Helper scripts
REGISTRY_BUILDER="/usr/local/bin/mesh-registry-builder.sh"
IP_MANAGER="/usr/local/bin/mesh-ip-manager.sh"
REGISTRY_STATE_FILE="/var/run/mesh_node_registry"
ENCODER_PATH="/usr/local/bin/encoder.py"
BATCTL_PATH="/usr/sbin/batctl"
THROUGHPUT_MEAN="/usr/local/bin/mesh-throughput-mean.sh"
RADIO_STATE_SYNC="/usr/local/bin/mesh-radio-state.py"
CONFIG_SYNC="/usr/local/bin/mesh-config-sync.py"
CONFIG_ROLLBACK="/usr/local/bin/mesh-config-rollback.sh"
HALOW_MCS_SUMMARY="/usr/local/bin/halow-mcs-summary.py"

# --- State Variables ---
LAST_PUBLISHED_PAYLOAD=""
LAST_PUBLISH_TIME=0
PUBLISH_INTERVAL=180  # Publish every 3 minutes

# Identity (hostname, MACs, syncthing ID) does not change while we are up, so
# it goes out on its own Alfred type and only often enough to stay resident.
# Alfred purges any record it has not seen for ALFRED_DATA_TIMEOUT = 600 s, so
# at 270 s a publish can fail once and the record still survives.
LAST_IDENTITY_PUBLISH=0
LAST_ACK_PUBLISHED=""
IDENTITY_PUBLISH_INTERVAL=270

log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] - NODE-MGR-STATIC: $1" >&2
}


# ==============================================================================
# === GATEWAY DETECTION ===
# ==============================================================================
# Gateway state is owned by manet-uplink-dispatch.sh. Node manager only
# asks it to reconcile periodically before publishing status to Alfred.
GATEWAY_STATE_FILE="/var/run/mesh-gateway.state"
LAST_GW_CHECK=0
GW_CHECK_INTERVAL=60

detect_and_update_gateway_state() {
    local NOW
    NOW=$(date +%s)

    local time_since_check=$(( NOW - LAST_GW_CHECK ))
    if [ "$time_since_check" -lt "$GW_CHECK_INTERVAL" ] && [ -f "$GATEWAY_STATE_FILE" ]; then
        return
    fi

    LAST_GW_CHECK=$NOW
    [ -x /usr/local/bin/manet-uplink-dispatch.sh ] && /usr/local/bin/manet-uplink-dispatch.sh reconcile >/dev/null 2>&1 || true
}

# ==============================================================================
# GPS time source
# ==============================================================================
# A node holding a live GPS fix disciplines its clock from gpsd's SHM 0
# refclock. That costs no network traffic at all — the refclock is shared
# memory, not a peer — so such a node keeps chrony running and serves time to
# the mesh, giving GPS-less nodes something to do their one-shot sync against.
#
# Gateways advertise themselves through mesh-ntp.state, which is owned by
# ethernet-autodetect.sh and deleted by it on carrier loss. This marker is kept
# separate so the two owners never race to remove each other's state; the
# published flag is the OR of the two.
#
# Which config chrony runs with is deliberately not managed here. That is owned
# by provision-mesh.sh, ethernet-autodetect.sh and the networkd-dispatcher off
# hook, and a third writer would reintroduce exactly the race this file avoids.
GPS_NTP_STATE_FILE="/var/run/mesh-ntp-gps.state"
GPS_STATUS_FILE="/run/gps_status.json"
GPS_FIX_MAX_AGE=60      # seconds before a status file counts as stale
LAST_GPS_CHECK=0
GPS_CHECK_INTERVAL=60

gps_has_live_fix() {
    python3 - "$GPS_STATUS_FILE" "$GPS_FIX_MAX_AGE" <<'PY'
import json, sys, time
try:
    with open(sys.argv[1]) as f:
        d = json.load(f)
except Exception:
    sys.exit(1)
if not d.get('has_fix'):
    sys.exit(1)
# gps-reader stamps every write. A frozen file means the daemon died or hung
# still holding a fix, and time from a dead reader is not time we should serve.
if time.time() - d.get('timestamp', 0) > float(sys.argv[2]):
    sys.exit(1)
sys.exit(0)
PY
}

update_gps_time_source() {
    local NOW
    NOW=$(date +%s)
    [ $(( NOW - LAST_GPS_CHECK )) -lt "$GPS_CHECK_INTERVAL" ] && return
    LAST_GPS_CHECK=$NOW

    if gps_has_live_fix; then
        # chrony must actually be running for the SHM refclock to be read.
        systemctl is-active --quiet chrony.service || systemctl start chrony.service
        touch "$GPS_NTP_STATE_FILE"
    else
        # Stop advertising, but leave chrony alone: on a node whose chrony.conf
        # has no network sources it is idle rather than chatty, and stopping it
        # would only slow re-acquisition when the fix comes back.
        rm -f "$GPS_NTP_STATE_FILE"
    fi
}

is_ntp_time_source() {
    [ -f /var/run/mesh-ntp.state ] || [ -f "$GPS_NTP_STATE_FILE" ]
}

get_current_freq() {
    local conf_file=$1
    grep -oP 'frequency=\K[0-9]+' "$conf_file" 2>/dev/null | head -1
}

radio_iface_enabled() {
    python3 - "$1" <<'PY'
import json, sys
iface = sys.argv[1]
try:
    with open('/var/lib/mesh_radio_state.json') as f:
        state = json.load(f).get('desired', {}).get(iface, 'up')
except Exception:
    state = 'up'
sys.exit(1 if state == 'down' else 0)
PY
}

collect_radio_mcs() {
    WLAN0_TX_MCS=""; WLAN0_RX_MCS=""
    WLAN1_TX_MCS=""; WLAN1_RX_MCS=""
    WLAN2_TX_MCS=""; WLAN2_RX_MCS=""
    [ -x "$HALOW_MCS_SUMMARY" ] || return 0
    for iface in wlan0 wlan1 wlan2; do
        [ -d "/sys/class/net/$iface" ] || continue
        eval "$("$HALOW_MCS_SUMMARY" --iface "$iface" --shell 2>/dev/null || true)"
    done
}

load_mesh_wpa_confs() {
    local mesh_ifaces=()

    if [ -f /var/lib/mesh_if ]; then
        mapfile -t mesh_ifaces < /var/lib/mesh_if
    fi

    # The 5 GHz radio is absent from mesh_if when it is reserved for AP duty
    # (ethernet-autodetect moves it between hostapd and the mesh), so a second
    # entry is optional — no wlan1 fallback.
    WPA_IFACE_2_4="${mesh_ifaces[0]:-wlan0}"
    WPA_IFACE_5_0="${mesh_ifaces[1]:-}"
    WPA_CONF_2_4="/etc/wpa_supplicant/wpa_supplicant-${WPA_IFACE_2_4}.conf"
    WPA_CONF_5_0=""
    [ -n "$WPA_IFACE_5_0" ] && WPA_CONF_5_0="/etc/wpa_supplicant/wpa_supplicant-${WPA_IFACE_5_0}.conf"
}

ensure_static_iface_channel() {
    local iface=$1 conf=$2 static_freq=$3 band=$4

    [ -n "$iface" ] || return 0
    if [ ! -f "$conf" ]; then
        log "Static mesh WPA config not ready for $band: $conf"
        return 0
    fi

    local freq
    freq=$(get_current_freq "$conf")
    [ "$freq" = "$static_freq" ] && return 0

    log "Correcting $band to static channel $static_freq"
    sed -i "s/frequency=.*/frequency=${static_freq}/" "$conf"
    if radio_iface_enabled "$iface"; then
        log "Restarting wpa_supplicant@${iface}..."
        systemctl restart "wpa_supplicant@${iface}.service"
        sleep 5
    fi
}

ensure_static_channels() {
    load_mesh_wpa_confs
    ensure_static_iface_channel "$WPA_IFACE_2_4" "$WPA_CONF_2_4" "$STATIC_FREQ_2_4" "2.4 GHz"
    ensure_static_iface_channel "$WPA_IFACE_5_0" "$WPA_CONF_5_0" "$STATIC_FREQ_5_0" "5 GHz"
}

is_hosting_service() {
	if systemctl is-active --quiet mediamtx.service; then
        local IPV4_NETWORK=""
	# Source the network configuration
	if [ -f /etc/mesh.conf ]; then
	    # Parse the config file
	    while IFS='=' read -r key value; do
	        [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
	        case "$key" in
	            ipv4_network)
	                IPV4_NETWORK="$value"
	                ;;
	        esac
	    done < /etc/mesh.conf
	fi
        [ -z "$IPV4_NETWORK" ] && return 1

        local CALC_OUTPUT=$(manet-ipcalc.sh "$IPV4_NETWORK" 2>/dev/null)
        local FIRST_IP=$(echo "$CALC_OUTPUT" | awk '/HostMin/ {print $2}')
        local MEDIAMTX_IPV4_VIP="${FIRST_IP%.*}.$((${FIRST_IP##*.} + 1))"
        ip addr show dev "$CONTROL_IFACE" | grep -q "inet $MEDIAMTX_IPV4_VIP/" && return 0
    fi
    return 1
}

is_hosting_mumble_service() {
    if systemctl is-active --quiet mumble-server.service; then
        if [ -f /etc/mesh.conf ]; then
            while IFS='=' read -r key value; do
                [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
                case "$key" in
                    ipv4_network)
                        IPV4_NETWORK="$value"
                        ;;
                esac
            done < /etc/mesh.conf
        fi

        local CALC_OUTPUT
        CALC_OUTPUT=$(manet-ipcalc.sh "$IPV4_NETWORK" 2>/dev/null)
        local FIRST_IP
        FIRST_IP=$(echo "$CALC_OUTPUT" | awk '/HostMin/ {print $2}')
        local MUMBLE_IPV4_VIP="${FIRST_IP%.*}.$((${FIRST_IP##*.} + 2))"
        ip addr show dev "$CONTROL_IFACE" | grep -q "inet $MUMBLE_IPV4_VIP/" && return 0
    fi
    return 1
}

# === MAIN SETUP ===
log "Starting Mesh Node Manager (Static Channel Mode)."
log "Static channels: 2.4G=${STATIC_FREQ_2_4}, 5G=${STATIC_FREQ_5_0}"
MY_MAC=$(cat "/sys/class/net/${CONTROL_IFACE}/address")
log "Node MAC: ${MY_MAC}"

# Ensure we're on static channels at startup
ensure_static_channels

# === MAIN LOOP ===
while true; do
    NOW=$(date +%s)

    # === ALFRED RADIO STATE SYNC ===
    # Global radio up/down changes are staged through Alfred and only applied
    # after all nodes have ACKed the same version.
    [ -x "$RADIO_STATE_SYNC" ] && "$RADIO_STATE_SYNC" sync || true

    # === ALFRED CONFIG SYNC ===
    # Same shape for mesh configuration: stage what the operator broadcast,
    # publish an ACK, and apply once activate_at passes.
    [ -x "$CONFIG_SYNC" ] && "$CONFIG_SYNC" sync || true

    # A dangerous config change can take the mesh down. This is the node
    # deciding, on its own, whether the change worked or has to be undone.
    [ -x "$CONFIG_ROLLBACK" ] && "$CONFIG_ROLLBACK" check || true

    # An ACK is only useful if peers see it promptly, so a change here brings
    # the next telemetry publish forward instead of waiting out the interval.
    CURRENT_ACK=$(cat /var/run/mesh_config_ack_version 2>/dev/null || echo "")
    if [ "$CURRENT_ACK" != "$LAST_ACK_PUBLISHED" ]; then
        LAST_PUBLISH_TIME=0
        LAST_ACK_PUBLISHED="$CURRENT_ACK"
    fi

    # Load current chunk assignment from IP manager
    MY_CHUNK=0
    if [ -f /var/run/my_ipv4_chunk ]; then
        MY_CHUNK=$(cat /var/run/my_ipv4_chunk)
    fi
    # === PERIODIC CHANNEL CHECK ===
    # Verify we haven't drifted from static channels (safety check)
    ensure_static_channels
    
    # === REGISTRY BUILD ===
    [ -x "$REGISTRY_BUILDER" ] && "$REGISTRY_BUILDER"
    
    # === IP MANAGEMENT ===
    [ -x "$IP_MANAGER" ] && "$IP_MANAGER"
    
    # === PUBLISH IDENTITY (Alfred type 67) ===
    # Hostname, MACs and syncthing ID do not change while we are up, so they
    # ride their own type and only refresh often enough to stay resident.
    if [ $((NOW - LAST_IDENTITY_PUBLISH)) -ge $IDENTITY_PUBLISH_INTERVAL ]; then
        # br0's MAC must come first: encoder.py drops it, because Alfred
        # already stamps every record we publish with it.
        ALL_MACS=("$MY_MAC")
        for iface in /sys/class/net/wlan* /sys/class/net/bat0 /sys/class/net/end0; do
            iface=$(basename "$iface")
            if [ -d "/sys/class/net/$iface" ]; then
                MAC=$(cat "/sys/class/net/$iface/address" 2>/dev/null)
                [ -n "$MAC" ] && ALL_MACS+=("$MAC")
            fi
        done

        CURRENT_IPV4=$(ip addr show dev "$CONTROL_IFACE" 2>/dev/null | grep -oP 'inet \K[\d.]+' | head -1)
        SYNCTHING_ID=$(runuser -u radio -- syncthing --device-id 2>/dev/null || echo "")

        IDENTITY_ARGS=(
            "--hostname" "$(hostname)"
            "--mac-addresses" "${ALL_MACS[@]}"
            "--syncthing-id" "$SYNCTHING_ID"
            "--ipv4-chunk" "$MY_CHUNK"
        )
        [ -n "$CURRENT_IPV4" ] && IDENTITY_ARGS+=("--ipv4-address" "$CURRENT_IPV4")

        IDENTITY_PAYLOAD=$("$ENCODER_PATH" identity "${IDENTITY_ARGS[@]}" 2>/dev/null)
        if [ -n "$IDENTITY_PAYLOAD" ]; then
            echo -n "$IDENTITY_PAYLOAD" | alfred -s $ALFRED_IDENTITY_TYPE
            LAST_IDENTITY_PUBLISH=$NOW
        else
            log "WARN: identity encoder produced no payload: $("$ENCODER_PATH" identity "${IDENTITY_ARGS[@]}" 2>&1 >/dev/null | tr '\n' ' ')"
        fi
    fi

    # === PUBLISH TELEMETRY (Alfred type 68) ===
    time_since_publish=$((NOW - LAST_PUBLISH_TIME))

    if [ $time_since_publish -ge $PUBLISH_INTERVAL ]; then
        log "Publishing status to Alfred..."

        # Not a positional field: `batctl o` shifts columns on the starred
        # (selected) route, so $3 is the last-seen timestamp there. See
        # mesh-throughput-mean.sh.
        MEAN_THROUGHPUT=$("$THROUGHPUT_MEAN" 2>/dev/null || echo 0)

        # Service flags
        detect_and_update_gateway_state
        update_gps_time_source
        IS_GATEWAY_FLAG=$([ -f /var/run/mesh-gateway.state ] && echo "--is-internet-gateway" || echo "")
        GATEWAY_IFACE=$(cat /var/run/upstream_iface 2>/dev/null || echo "")
        IS_NTP_FLAG=$(is_ntp_time_source && echo "--is-ntp-server" || echo "")
        IS_MEDIAMTX_FLAG=$(is_hosting_service && echo "--is-mediamtx-server" || echo "")
        IS_MUMBLE_FLAG=$(is_hosting_mumble_service && echo "--is-mumble-server" || echo "")

        collect_radio_mcs

        # Encode (no scan data, no limp mode, no tourguide in static mode)
        ENCODER_ARGS=(
            "--mean-throughput-mbps" "$MEAN_THROUGHPUT"
            "--timestamp" "$NOW"
            "--config-ack-version" "$(cat /var/run/mesh_config_ack_version 2>/dev/null || echo "")"
            "--data-channel-2-4" "$STATIC_FREQ_2_4"
            "--data-channel-5-0" "$STATIC_FREQ_5_0"
            "--wifi-24-tx-mcs" "${WLAN0_TX_MCS:-}"
            "--wifi-24-rx-mcs" "${WLAN0_RX_MCS:-}"
            "--wifi-5-tx-mcs" "${WLAN1_TX_MCS:-}"
            "--wifi-5-rx-mcs" "${WLAN1_RX_MCS:-}"
            "--halow-tx-mcs" "${WLAN2_TX_MCS:-}"
            "--halow-rx-mcs" "${WLAN2_RX_MCS:-}"
            "--halow-mcs-peer" "${WLAN2_MCS_PEER:-}"
        )
        [ -n "$IS_GATEWAY_FLAG" ] && ENCODER_ARGS+=("$IS_GATEWAY_FLAG")
        [ -n "$GATEWAY_IFACE" ] && ENCODER_ARGS+=("--gateway-iface" "$GATEWAY_IFACE")
        [ -n "$IS_NTP_FLAG" ] && ENCODER_ARGS+=("$IS_NTP_FLAG")
        [ -n "$IS_MEDIAMTX_FLAG" ] && ENCODER_ARGS+=("$IS_MEDIAMTX_FLAG")
        [ -n "$IS_MUMBLE_FLAG" ] && ENCODER_ARGS+=("$IS_MUMBLE_FLAG")
        BATT_PCT=$(python3 -c "import json;d=json.load(open('/run/battery_status.json'));p=d.get('percentage');print('' if p is None else p)" 2>/dev/null)
        [ -n "$BATT_PCT" ] && ENCODER_ARGS+=("--battery-percentage" "$BATT_PCT")
        UPTIME_SECS=$(awk '{print int($1)}' /proc/uptime 2>/dev/null)
        [ -n "$UPTIME_SECS" ] && ENCODER_ARGS+=("--uptime-seconds" "$UPTIME_SECS")
        CPU_LOAD=$(awk '{print $1}' /proc/loadavg 2>/dev/null)
        [ -n "$CPU_LOAD" ] && ENCODER_ARGS+=("--cpu-load-average" "$CPU_LOAD")

        # --- GPS Location ---
        # A stale file is rejected as well as a missing fix. gps-reader stamps
        # every write, so a frozen timestamp means it died or hung while still
        # holding a fix — and a moving node would otherwise keep beaconing the
        # position it had when the reader stopped. Only has_fix was checked
        # before, so that stale position was published indefinitely.
        GPS_LAT=""; GPS_LON=""; GPS_ALT=""
        if [ -f "$GPS_STATUS_FILE" ]; then
            eval "$(python3 -c "
import json, sys, time
try:
    d = json.load(open(sys.argv[1]))
    if d.get('has_fix') and time.time() - d.get('timestamp', 0) <= float(sys.argv[2]):
        print('GPS_LAT=' + str(d['latitude']))
        print('GPS_LON=' + str(d['longitude']))
        print('GPS_ALT=' + str(d['altitude']))
except Exception:
    pass
" "$GPS_STATUS_FILE" "$GPS_FIX_MAX_AGE" 2>/dev/null)"
        fi
        [ -n "$GPS_LAT" ] && ENCODER_ARGS+=("--latitude" "$GPS_LAT" "--longitude" "$GPS_LON" "--altitude" "$GPS_ALT")

        CURRENT_PAYLOAD=$("$ENCODER_PATH" telemetry "${ENCODER_ARGS[@]}" 2>/dev/null)
        if [ -z "$CURRENT_PAYLOAD" ]; then
            # re-run only on failure, to surface why nothing was published
            log "WARN: encoder produced no payload, not publishing: $("$ENCODER_PATH" telemetry "${ENCODER_ARGS[@]}" 2>&1 >/dev/null | tr '\n' ' ')"
        fi
        
        if [ -n "$CURRENT_PAYLOAD" ]; then
            echo -n "$CURRENT_PAYLOAD" | alfred -s $ALFRED_DATA_TYPE
            LAST_PUBLISHED_PAYLOAD="$CURRENT_PAYLOAD"
            LAST_PUBLISH_TIME=$NOW
        fi
    fi
	# === RUN SERVICE ELECTIONS ===
	for election_script in /usr/local/bin/*-election.sh; do
	    if [[ -f "$election_script" && -x "$election_script" ]]; then
	        # Skip channel-election.sh since we're static
	        [[ "$election_script" =~ channel-election ]] && continue
	        # Skip mediamtx-election.sh if MTX not enabled
	        if [[ "$election_script" =~ mediamtx-election ]]; then
	            MTX_ENABLED=$(grep "^mtx=" /etc/mesh.conf 2>/dev/null | cut -d'=' -f2)
	            [[ "$MTX_ENABLED" != "y" ]] && continue
	        fi
	        if [[ "$election_script" =~ mumble-election ]]; then
	            MUMBLE_ENABLED=$(grep "^mumble=" /etc/mesh.conf 2>/dev/null | cut -d'=' -f2)
	            [[ "$MUMBLE_ENABLED" != "y" ]] && continue
	        fi
	        "$election_script" &    # ← NOW runs only if checks pass
	    fi
	done
    sleep "$MONITOR_INTERVAL"
done

log "Main loop exited unexpectedly. Restarting..."
exit 1
