[server]
host-name=manet
host-name-from-machine-id=no
use-ipv4=yes
use-ipv6=no
allow-interfaces=wlan3

[wide-area]
enable-wide-area=no

[publish]
publish-hinfo=no
publish-workstation=no
publish-domain=yes

[reflector]
enable-reflector=no
